version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: bauhauswatch-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9202:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9202/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    image: bauhauswatch:latest
    build: .
    container_name: bauhauswatch
    restart: unless-stopped
    ports:
      - "5303:8000"
    volumes:
      - ./app:/app/app
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9202

volumes:
  elasticsearch_data: