version: '3'
services:
  app:
    image: bauhauswatch:latest
    build: .
    container_name: bauhauswatch
    restart: unless-stopped
    ports:
      - "5303:8000"
    volumes:
      - ./app:/app/app